apiVersion: v1
kind: Service
metadata:
  name: kcna-health-service
  labels:
    app.kubernetes.io/name: kcna-health-demo
    app.kubernetes.io/part-of: kcna-capstone
spec:
  type: ClusterIP
  selector:
    app: kcna-health-demo
    tier: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
