name: Kubernetes Manifests & Lint CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  validate-k8s:
    name: Validate Kubernetes Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Dry-Run Manifest Validation
        run: |
          echo "Checking YAML syntax and Kubernetes schemas..."
          for file in $(find . -name "*.yaml" -not -path "./.github/*"); do
            echo "Validating $file..."
            kubectl apply --dry-run=client -f "$file"
          done

      - name: Run Kubeconform Schema Validation
        uses: yannh/kubeconform-action@v0.1.0
        with:
          k8s-version: 'v1.30.0'
          files: '01-configmaps/*.yaml 02-secrets/*.yaml 03-labels-and-annotations/*.yaml 04-probes/*.yaml 05-capstone-app/*.yaml'
