apiVersion: v1
kind: Secret
metadata:
  name: web-tls-cert
  labels:
    app.kubernetes.io/name: kcna-secrets-demo
    app.kubernetes.io/part-of: kcna-study-guide
# KCNA Exam Highlight:
# kubernetes.io/tls requires exactly two keys: 'tls.crt' and 'tls.key'
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIICvDCCAaQCCQCf8v4k/0rR2jANBgkqhkiG9w0BAQsFADAgMR4wHAYDVQQDDBVr
    Y25hLWRlbW8uZXhhbXBsZS5jb20wHhcNMjYwMTAxMDAwMDAwWhcNMjcwMTAxMDAw
    MDAwWjAgMR4wHAYDVQQDDBVrY25hLWRlbW8uZXhhbXBsZS5jb20wggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQC6g...KCNA...DEMO...CERT...
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC6g...KCNA...
    DEMO...KEY...
    -----END PRIVATE KEY-----
